//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TravianBot.Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using TravianBot.Core.Log;
	using TravianBot.Core.Models;
	using TravianBot.Core.State;

	public class Client
	{
        private static Client client;

        public static Client Default
        {
            get
            {
                if (client == null)
                    client = new Client();
                return client;
            }
        }

        private Client()
        {
            
        }

        public ISetting Setting { get { return Models.Setting.Default; } }

        public HtmlManager HtmlManager
        {
            get;
            set;
        }

        public IEventLogger EventLogger
        {
            get;
            set;
        }

        public ILogger Logger
        {
            get;
            set;
        }

        public StateMachine StateMachine
        {
            get;
            set;
        }

        public IEnumerable<Village> Villages
        {
            get;
            set;
        }

        public void GoUrl(string url)
        {

        }

    }
}

