//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TravianBot.Core
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;
    using System.Text;

    public class HtmlManager : INotifyPropertyChanged
	{
        public event PropertyChangedEventHandler PropertyChanged;

        public string Html
        {
            get
            {
                return Html;
            }
            set
            {
                Html = value;
            }
        }
    }
}

