//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace TravianBot.Core.Models
{
	/// <summary>
	/// Database       : TravianBot
	/// Data Source    : C:\Users\UtahC\Documents\Visual Studio 2015\Projects\TravianBot\TravianBot.Core\TravianBot.mdb
	/// Server Version : 04.00.0000
	/// </summary>
	public partial class TravianBotDB : LinqToDB.Data.DataConnection
	{
		public ITable<DB_Building> DB_Buildings { get { return this.GetTable<DB_Building>(); } }
		public ITable<DB_User>     DB_Users     { get { return this.GetTable<DB_User>(); } }
		public ITable<DB_Village>  DB_Villages  { get { return this.GetTable<DB_Village>(); } }

		public TravianBotDB()
		{
			InitDataContext();
		}

		public TravianBotDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("DB_Buildings")]
	public partial class DB_Building
	{
		[PrimaryKey, Identity] public int    DB_Id        { get; set; } // Long
		[Column,     Nullable] public int?   BuildingId   { get; set; } // Long
		[Column,     Nullable] public int?   VillageId    { get; set; } // Long
		[Column,     Nullable] public int?   Level        { get; set; } // Long
		[Column,     Nullable] public string BuildingType { get; set; } // text(255)
	}

	[Table("DB_Users")]
	public partial class DB_User
	{
		[PrimaryKey, Identity] public int    DB_Id           { get; set; } // Long
		[Column,     Nullable] public string Server          { get; set; } // text(255)
		[Column,     Nullable] public string Account         { get; set; } // text(255)
		[Column,     Nullable] public string Password        { get; set; } // text(255)
		[Column,     Nullable] public string Speed           { get; set; } // text(255)
		[            Identity] public bool   IsLowResolution { get; set; } // Bit
		[Column,     Nullable] public string UserAgent       { get; set; } // text(255)
		[            Identity] public bool   IsUseProxy      { get; set; } // Bit
		[Column,     Nullable] public string ProxyHost       { get; set; } // text(255)
		[Column,     Nullable] public int?   ProxyPort       { get; set; } // Long
		[Column,     Nullable] public string ProxyLogin      { get; set; } // text(255)
		[Column,     Nullable] public string ProxyPassword   { get; set; } // text(255)
		[Column,     Nullable] public string Tribe           { get; set; } // text(255)
	}

	[Table("DB_Villages")]
	public partial class DB_Village
	{
		[PrimaryKey, Identity] public int    DB_Id       { get; set; } // Long
		[Column,     Nullable] public int?   VillageId   { get; set; } // Long
		[Column,     Nullable] public string VillageName { get; set; } // text(255)
		[Column,     Nullable] public int?   X           { get; set; } // Long
		[Column,     Nullable] public int?   Y           { get; set; } // Long
		[            Identity] public bool   IsCapital   { get; set; } // Bit
	}

	public static partial class TableExtensions
	{
		public static DB_Building Find(this ITable<DB_Building> table, int DB_Id)
		{
			return table.FirstOrDefault(t =>
				t.DB_Id == DB_Id);
		}

		public static DB_User Find(this ITable<DB_User> table, int DB_Id)
		{
			return table.FirstOrDefault(t =>
				t.DB_Id == DB_Id);
		}

		public static DB_Village Find(this ITable<DB_Village> table, int DB_Id)
		{
			return table.FirstOrDefault(t =>
				t.DB_Id == DB_Id);
		}
	}
}
