//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TravianBot.Core.Enums
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum Tribes : int
	{
		None,
		Romans,
		Teutons,
		Guals,
	}
}
