//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TravianBot.Core.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using TravianBot.Core.Enums;
	using TravianBot.Core.Information;

	public class Building : DB_Building
    {
        private int buildingId;
        private int villageId;
        private int level;
        private Buildings buildingType;
        private BuildingInfo info;

		public new int BuildingId
		{
            get
            {
                return buildingId;
            }
            set
            {
                Set(() => BuildingId, ref buildingId, value);
            }
        }

		public new int VillageId
		{
            get
            {
                return villageId;
            }
            set
            {
                Set(() => VillageId, ref villageId, value);
            }
        }

		public new int Level
		{
            get
            {
                return level;
            }
            set
            {
                Set(() => Level, ref level, value);
            }
        }

		public new Buildings BuildingType
		{
            get
            {
                return buildingType;
            }
            set
            {
                Set(() => BuildingType, ref buildingType, value);
            }
        }

		public BuildingInfo Info
		{
            get
            {
                return info;
            }
            set
            {
                Set(() => Info, ref info, value);
            }
        }

	}

    public partial class DB_Building : GalaSoft.MvvmLight.ObservableObject
    {

    }
}

