//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TravianBot.Core.Log
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface ILogger 
	{
		void Write(object string text);

		void Write(object string text, object System.Windows.Media.Brush color);

	}
}

