//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TravianBot.Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using TravianBot.Core.State;

	public class Client
	{
		public virtual ISettings Settings
		{
			get;
			set;
		}

		public virtual HtmlManager HtmlManager
		{
			get;
			set;
		}

		public virtual JavascriptManager JavascriptManager
		{
			get;
			set;
		}

		public virtual StateMachine StateMachine
		{
			get;
			set;
		}

	}
}

