//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TravianBot.Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using TravianBot.Core.Enums;

	public interface ISettings 
	{
		string Account { get;set; }

		Uri Server { get;set; }

		string Password { get;set; }

		int Speed { get;set; }

		bool IsLowResolution { get;set; }

		string UserAgent { get;set; }

		string IsUseProxy { get;set; }

		string ProxyLogin { get;set; }

		string ProxyPassword { get;set; }

		Tribes Tribe { get;set; }

		ILogicSettings Logic { get;set; }

		void Save();

		void Read();

	}
}

