//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TravianBot.Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Settings : ISettings
	{
		public virtual void Save()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Read()
		{
			throw new System.NotImplementedException();
		}

		private void Generate()
		{
			throw new System.NotImplementedException();
		}

	}
}

