//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TravianBot.Core.State
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading;
    using System.Threading.Tasks;

    public class StateMachine
	{
		public StateBase State
		{
			get;
			set;
		}

        public void Start(CancellationToken cancellationToken)
        {
            Task.Run(async () =>
            {
                while (State != null)
                {
                    State = await State.Start(cancellationToken);
                    await Task.Delay(1000);
                }
            });
        }

	}
}

