//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TravianBot.Core.State
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class TransportingSmithyState : IState
	{
		public virtual IState Excute()
		{
			throw new System.NotImplementedException();
		}

	}
}

